pub mod autoscroll;
mod callout;
pub mod dialogs;
pub mod editor_area;
pub mod editor_content;
pub mod scrolling;
pub mod search_replace;
pub mod settings;
pub mod status_bar;
pub mod tab_drag;
pub mod tab_overflow;
pub mod tab_strip;
pub mod tile_header;
pub mod transition;
pub mod widget_ids;
